name: API workflow

on: [ push, pull_request ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Run tests
        run: poetry run python -m pytest --cov=tests/ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

